apiVersion: v1
kind: Service
metadata:
  name: vectordb-coordinator
  namespace: vectordb
  labels:
    app: vectordb-coordinator
spec:
  type: NodePort
  selector:
    app: vectordb-coordinator
  ports:
    - port: 50050
      targetPort: 50050
      nodePort: 30050
      name: grpc
